openapi: 3.0.0
info:
  title: Customer Management API
  description: API for managing customer information
  version: 1.0.0

paths:
  /api/customers:
    get:
      summary: Retrieve all customers
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Customer'
    post:
      summary: Add a new customer
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Customer'
      responses:
        '201':
          description: Customer created successfully
        '400':
          description: Bad request

  /api/customers/{ID}:
    get:
      summary: Retrieve a specific customer
      parameters:
        - name: ID
          in: path
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Customer'
        '404':
          description: Customer not found
    put:
      summary: Update an existing customer
      parameters:
        - name: ID
          in: path
          required: true
          schema:
            type: integer
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Customer'
      responses:
        '204':
          description: Customer updated successfully
        '400':
          description: Bad request
        '404':
          description: Customer not found
    delete:
      summary: Delete a customer
      parameters:
        - name: ID
          in: path
          required: true
          schema:
            type: integer
      responses:
        '204':
          description: Customer deleted successfully
        '404':
          description: Customer not found

components:
  schemas:
    Customer:
      type: object
      properties:
        ID:
          type: integer
        Name:
          type: string
        Address:
          type: string
        Email:
          type: string
        Phone:
          type: string
        City:
          type: string
        State:
          type: string
        Zip:
          type: string
        Country:
          type: string
        Notes:
          type: string
        ContactName:
          type: string
        ContactPhone:
          type: string
        ContactEmail:
          type: string
        ContactTitle:
          type: string
        ContactNotes:
          type: string
      required:
        - Name
        - Email
        - Phone
